### ISSUE TITLE
Feasibility study for the merkle-like solution

### ISSUE THREAD

**Issue by homura** [ckb-js/kuai#6]
Cell model is UTxO-like, and it is hard for us as application developers to get working with it because of shared state, capacity management, and script combination.

An initial idea is that the Kuai framework provides a runtime that is used to help developers write CRUD-style programs that manage off-chain state and generate proofs to update the [merkle roots on-chain](https://ethereum.org/en/developers/tutorials/merkle-proofs-for-offline-data-integrity/), i.e., state is stored off-chain and only one merkle root is stored on-chain.

To implement the feature mentioned above, we first need to do some feasibility study, like

- dApp user identity via P2SH instead of P2PK(H)
- off-chain state transition replayed in the contract without a vm
- cross-dApp (contract) communication without a global sequencer
- and other...

**Comment by Keith-CY** [comment]
I think this consideration should be enriched and added to the proposal([General aggregation service section](https://github.com/ckb-js/topics/compare/add-draft-of-kuai-proposal?expand=1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R324))

**Comment by homura** [comment]
> I think this consideration should be enriched and added to the proposal

Does it mean that the info in the current proposal is not detailed enough, and we can add the description in this issue to the proposal?

**Comment by Keith-CY** [comment]
> > I think this consideration should be enriched and added to the proposal
> 
> Does it mean that the info in the current proposal is not detailed enough, and we can add the description in this issue to the proposal?

I think it's not detailed enough in the proposal, there's just a sentence briefly mentioning that `SMT-based` aggregation service will be provided, with no more direction or schedule of it.

We can grain the strategy and then add them to the proposal

**Comment by homura** [comment]
i see, we will make the merkle-like solution part of the proposal more detailed

**Comment by Keith-CY** [comment]
How is it going

**Comment by felicityin** [comment]
user: specifically, the user of a dApp

developer: developer who will use Kuai

# 1 Process

```mermaid
flowchart TB
  Actions["Action(s)"]
  Storage["MerkleXStorage"]

  subgraph Transaction
    direction LR
    subgraph Inputs
      MerkleRoot
    end

    subgraph Outputs
      MerkleRoot'
    end

    Inputs -.transition replay.-> Outputs
  end

  subgraph ActionExecutor
    Storage --> State
    State --> State'
    State' --> TransitionProof
    State' --> Storage
  end

  Actions -.-> Sequencer
  Sequencer --> ActionExecutor
  TransitionProof --> Transaction
```

- Action - A request from a user. Users only need to sign the calling method and parameters, rather than transaction. Because users may not know the state before and after the transaction.
- Sequencer - It is a pool of temporary actions similar to `mempool` in the blockchain. It will process the actions sequentially to avoid the UTxO concurrency issue.
- ActionExecutor - Execute the action to generate a new state. The state dependency graph will be recorded to ensure that proof can be generated when the transaction is initiated.
    
    An example of a state dependency diagram is as follows:
    
    ```mermaid
    graph TD;
    	action1 -.r.-> state1
      action1 -.w.-> state2
      action2 -.r.-> state2
      action2 -.w.-> state3
    ```
    
    In the figure above, action1 reads state1 and generates state2. Action2 reads state2 and generates state3. These dependent states will be used to generate merkle proof.
    
- MerkleXStorage - It is equivalent to a KV large table with infinite space (2 ** 256), and can quickly prove whether a certain state exists. Multiple actions occurred in a short time will share the same proof after the actions being processed by the ActionExecutor.
- To Be Determined -  Interaction between contracts. It may also need to ensure the atomicity of transaction across contracts. A clear design cannot be given for now. A fallback scheme is to use a global sequencer for cross contract scheduling, or to work with OpenTx protocol to construct transaction interactions across Kuai dApps.

# 2 Use case

Take the register of domain names as an example to describe how developers use the kuai.

For example, at the same time, multiple users send requests(or actions) to register domain names:

```jsx
action1:
{
	"method": "registerDomain",
  "params": {
    "domain": "kuai.bit",
    "_lock": {. "code_hash": "0x.1..." },
    "_signature": "0x.1..."
  }
}

action2:
{
	"method": "registerDomain",
  "params": {
    "domain": "kuai.bit",
    "_lock": {. "code_hash": "0x.2..." },
    "_signature": "0x.2..."
  }
}

action3:
{
	"method": "registerDomain",
  "params": {
    "domain": "kuai-new.bit",
    "_lock": {. "code_hash": "0x.3..." },
    "_signature": "0x.3..."
  }
}
```

Multiple actions will be processed by the sequencer sequentially. And action1 and action3 will go to the ActionExecutor. However, action2 will be rejected by the sequencer because it conflicts with action1.

Developers develop the `ActionExecutor` by Kuai to process actions. The process is roughly as follows:

```jsx
/*
	off-chain
*/

interface BuyDomainPayload {
  domain: string;
}

interface Context {
  requestFrom: LockLike;
  store: MerkleXStorage;
}

// call this method will auto generate the proof 
// for replaying state transition in the contract
// should be atomic
@transaction
async function registerDomain(context: Context, payload: BuyDomainPayload) {
  const user = context.requestFrom
  const holder = await context.store.get(["domain_holders", payload.domain])
  
  if (holder != null) throw new Error("the domain is in use")
  // ...

  await context.store.put(["domain_holders", context.requestFrom], payload.domain)
}
```

After action1 and action3 are processed by `registerDomain`, the state dependency graph will be recorded, and finally a transaction will be generated, which will include the proof of the state transition.

The state dependency diagram is as follows:

```mermaid
graph LR;
	state1["state1(lock1,null)"] -.r.-> action1 
  action1 -.w.-> state2["state2(lock1, kuai.bit)"] 
  action2["<del>action2(rejected)</del>"]
  state3["state3(lock2, null)"] -.r.-> action3 
  action3 -.w.-> state4["state4(lock2, kuai-dev.bit)"]
```

After the transaction is sent to the chain, it will be verified by the contract. The rough description is as follows:

**Comment by homura** [comment]
The merkle-like solution stores all the states directly as SMT to avoid the capacity management problem, but in last week's meeting, there was a requirement to let the state be stored directly in the cell, and let the developers choose which solution to use.

This is really a challenging requirement, and I tried to translate this requirement into another question: what kind of state is suitable to be split and stored directly on the chain? Perhaps we can classify states into two categories, one for contract states and one for rights and interests.


Most contracts are stateful, and most of the states within contracts are shared states, which are probably familiar to most developers, such as the current issuance of tokens and the issuance limit, which are used to control the issuance of tokens. Interests can be divided into qualitative interests and quantitative interests, which are often referred to as NFT and FT

When the state is categorized in this way, the transaction structure of action execution is as follows

```yaml
inputs:
  action_cell:
    type:
      args:
        # only the owner of the lock can generatge an action_cell
        lock_hash
    lock: <empty>
    data:
      contract_id
      call_method
      call_params
      approved_assets
        - approved_capacity
        - approved_udt_and_amount(s)
        - approved_nft(s)
  user_udt_cell:
    lock: # KuaiAssetLock
      args:
        lock_hash # hash of action_cell's change_or_redeem_lock
    type: udt_type_script
    data: udt_data
  user_nft_cell:
    lock:
      args:
        lock_hash # hash of action_cell's change_or_redeem_lock
    type: nft_type_script
    data: nft_data
  user_capacity_cell:
    lock: # KuaiAssetLock
      args:
        lock_hash
    contract_udt_cell:
      lock: kuai_contract_lock
    contract_nft_cell:
      lock: kuai_contract_lock
    contract_cell:
      lock: kuai_contract_lock # KuaiContractLock, config for upgrade policy
      data:
        ascii("Kuai/contract")
        contract_id
        smt_root
      witness:
        transition_proof
    action_cell2: # calls from another user
    action_cell3: # calls from another user
    ...
outputs:
  udt_change_cell
  nft_change_cell
  capacity_change_cell
  contract_cell
  lock: kuai_contract_lock
  data:
    ascii("Kuai/contract")
    contract_id
    new_smt_root
```


We need to discuss whether such a way is feasible, and if it is a feasible, then we are doing the continued refining of the design
